[package]
name = "martin-jason-alfredo/ultimatesystem"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Signal = "sleitnick/signal@2.0.3"
Trove = "sleitnick/trove@1.8.0"
Comm = "sleitnick/comm@1.0.1"

[server-dependencies]
ProfileStore = "lm-loleris/profilestore@1.0.3"